In [1]:
import sys
from pathlib import Path

repo_root = Path.cwd()
sys.path.append(str(repo_root.parent / "src"))

In [2]:
from ingestion.load_redial_action import load_redial_action, quick_stats
import pandas as pd

In [3]:
df_redial_action = load_redial_action("../data/raw/ReDial-action.txt")
quick_stats(df_redial_action)
df_redial_action.head()

Rows: 4583
Conversations: 336
Speakers: {'SYSTEM': 2322, 'USER': 2261}

,conv_id,turn_id,speaker,text,dialog_act,scores_raw,scores,is_overall
0,0,1,USER,Hi can you help me find a movie to watch,AskForRec,None,None,False
1,0,2,SYSTEM,"Yes, how about @187028 <It (2017)> ?",Recommend,None,None,False
2,0,3,USER,I don't really like horror movies what about t...,GiveFeedback,None,None,False
3,0,4,SYSTEM,@203424 <The Silence of the Lambs (1991)>,Recommend,None,None,False
4,0,5,USER,I have seen it and enjoyed it...One of my favo...,AddDetails,None,None,False

In [4]:
# Calculate satisfaction_mean and add label column
# Note: REDIAL-ACTION has no scores, so satisfaction_mean will be None
df_redial_action["satisfaction_mean"] = None

# Add label column if dialog_act exists
if "dialog_act" in df_redial_action.columns:
    df_redial_action["label"] = df_redial_action["dialog_act"]

In [5]:
# REDIAL-ACTION Statistics
import numpy as np

print("=" * 50)
print("REDIAL-ACTION Dataset Statistics")
print("=" * 50)
print(f"Num rows: {len(df_redial_action)}")
print(f"Num conversations: {df_redial_action['conv_id'].nunique()}")
print(f"Num OVERALL lines: {df_redial_action['is_overall'].sum()}")
print(f"\nSpeakers value counts:")
print(df_redial_action['speaker'].value_counts())
if 'label' in df_redial_action.columns:
    print(f"\nLabel value counts:")
    print(df_redial_action['label'].value_counts())
else:
    print("\nLabel column does not exist")
satisfaction_mean = df_redial_action['satisfaction_mean'].mean()
if pd.notna(satisfaction_mean):
    print(f"\nSatisfaction mean: {satisfaction_mean:.4f}")
else:
    print("\nSatisfaction mean: N/A (no scores available)")
print("\n" + "=" * 50)
print("Preview head():")
print("=" * 50)
df_redial_action.head()

==================================================
REDIAL-ACTION Dataset Statistics
==================================================
Num rows: 4583
Num conversations: 336
Num OVERALL lines: 0

Speakers value counts:
speaker
SYSTEM    2322
USER      2261
Name: count, dtype: int64

Label value counts:
label
OTH             1058
GiveFeedback     964
Explain          764
Recommend        500
AskForRec        394
AddDetails       333
Respond          286
Request          284
Name: count, dtype: int64

Satisfaction mean: N/A (no scores available)

==================================================
Preview head():
==================================================

,conv_id,turn_id,speaker,text,dialog_act,scores_raw,scores,is_overall,satisfaction_mean,label
0,0,1,USER,Hi can you help me find a movie to watch,AskForRec,None,None,False,None,AskForRec
1,0,2,SYSTEM,"Yes, how about @187028 <It (2017)> ?",Recommend,None,None,False,None,Recommend
2,0,3,USER,I don't really like horror movies what about t...,GiveFeedback,None,None,False,None,GiveFeedback
3,0,4,SYSTEM,@203424 <The Silence of the Lambs (1991)>,Recommend,None,None,False,None,Recommend
4,0,5,USER,I have seen it and enjoyed it...One of my favo...,AddDetails,None,None,False,None,AddDetails

In [6]:
df_redial_action.to_parquet("../data/processed/redial_action_turns.parquet", index=False)
print("Saved redial_action_turns.parquet")

Saved redial_action_turns.parquet